import PopularMovies from "@/components/Home/PopularMovies"
import PopularPeople from "@/components/Home/PopularPeople"
import PopularShows from "@/components/Home/PopularShows"
import { FetchedDataMovies, FetchedDataPeople, FetchedDataShows } from "@/types"
import Head from "next/head"

interface HomeProps {
  movies: FetchedDataMovies
  shows: FetchedDataShows
  people: FetchedDataPeople
}

export default function Home({ movies, shows, people }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Mooovies</h1>
      <PopularMovies movies={movies} />
      <PopularShows shows={shows} />
      <PopularPeople people={people} />
    </>
  )
}

export async function getStaticProps() {
  const [moviesRes, showsRes, peopleRes] = await Promise.all([
    fetch(
      `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.TMDB_API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/tv/popular?api_key=${process.env.TMDB_API_KEY}&language=en-US&page=1`
    ),
    fetch(
      ` https://api.themoviedb.org/3/person/popular?api_key=${process.env.TMDB_API_KEY}&language=en-US&page=1`
    ),
  ])

  const [movies, shows, people] = await Promise.all([
    moviesRes.json(),
    showsRes.json(),
    peopleRes.json(),
  ])

  return {
    props: {
      movies,
      shows,
      people,
    },
    revalidate: 21600,
  }
}
