import { FetchedData } from "@/types"
import Head from "next/head"

interface HomeProps {
  movies: FetchedData
}

export default function Home({ movies }: HomeProps) {
  console.log(movies)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello world</div>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch(
    `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.TMDB_API_KEY}&language=en-US&page=1`
  )
  const movies = await res.json()

  return {
    props: {
      movies,
    },
  }
}
